from __future__ import annotations

from typing import Any, Dict, Optional

from ..schemas import Assumption


DEFAULT_TOP_N = "DEFAULT_TOP_N"
DEFAULT_RANKING_BY_MARKET_VALUE = "DEFAULT_RANKING_BY_MARKET_VALUE"
DEFAULT_TIME_WINDOW_MOST_RECENT = "DEFAULT_TIME_WINDOW_MOST_RECENT"
DEFAULT_SORT_DESC = "DEFAULT_SORT_DESC"
DEFAULT_METRIC_MARKET_VALUE = "DEFAULT_METRIC_MARKET_VALUE"

INFER_ENTITY_FUND = "INFER_ENTITY_FUND"
INFER_ENTITY_SECURITY = "INFER_ENTITY_SECURITY"

INFER_METRIC_MARKET_VALUE = "INFER_METRIC_MARKET_VALUE"
INFER_METRIC_TOTAL_RETURN = "INFER_METRIC_TOTAL_RETURN"
INFER_METRIC_WEIGHT_PCT = "INFER_METRIC_WEIGHT_PCT"
INFER_METRIC_SHARES = "INFER_METRIC_SHARES"

INFER_ANALYSIS_RANK = "INFER_ANALYSIS_RANK"
INFER_ANALYSIS_SNAPSHOT = "INFER_ANALYSIS_SNAPSHOT"
INFER_ANALYSIS_TREND = "INFER_ANALYSIS_TREND"

INFER_SCOPE_UNIVERSE = "INFER_SCOPE_UNIVERSE"
INFER_SCOPE_SINGLE = "INFER_SCOPE_SINGLE"

INFER_TIME_AXIS_REPORT_DATE = "INFER_TIME_AXIS_REPORT_DATE"
INFER_TIME_AXIS_MONTH_END = "INFER_TIME_AXIS_MONTH_END"


def make_assumption(code: str, message: str, details: Optional[Dict[str, Any]] = None) -> Assumption:
    return Assumption(code=code, message=message, details=details or {})